name: Test SSH Connection

on:
  push:
    branches: [ "master" ]

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test SSH Connection
      run: |
        # Create a temporary file for the SSH key
        echo "${{ secrets.SSH_MY_MAC_KEY }}" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        
        # Attempt to SSH into the Raspberry Pi and echo a message
        ssh -i /tmp/ssh_key dandelion@192.168.86.30 "echo 'Connected successfully!'"
        
        # Clean up the temporary SSH key file
        rm /tmp/ssh_key
